Source/SignalRTest/Models/ExquisiteCorpse.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SignalRTest.Models
{
    public class ExquisiteCorpse
    {
        public string RoomId { get; set; }
        public List<string> Participants { get; set; }
        public bool HasStarted { get; set; }

        public ExquisiteCorpse()
        {
            Participants = new List<string>();
            HasStarted = false;
        }
    }
}

Source/SignalRTest/Controllers/DrawingController.cs
using Microsoft.AspNet.SignalR;
using SignalRTest.Models;
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SignalRTest.Controllers
{
    public class DrawingController : Controller
    {
        public static ConcurrentDictionary<string, ExquisiteCorpse> RoomId_Game = new ConcurrentDictionary<string, ExquisiteCorpse>(); // TO DO - why am i using ConcurrentDictionary instead of just dictionary?

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult OtherPage()
        {
            var hub = GlobalHost.ConnectionManager.GetHubContext<DrawingHub>();
            hub.Clients.All.broadcastMessage("IIS", "Someone is viewing the other page.");
            return View();
        }
    }
}

Source/SignalRTest/Views/Drawing/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div id="LobbyContainer">
    <div id="CreateOrJoinGame">
        Join or Create Game: <input type="text" id="GameName" /><br/>
        <button id="JoinGameButton" type="button" onclick="Lobby.joinOrCreateGame();" style="display:none;">Join</button>
    </div>
    <div id="OpenGames">
        <h3>Open Games</h3>
        <i>Click to join!</i>
        <ul id="gameList">
        </ul>
    </div>
</div>

<div id="GameContainer" style="display:none;">
    <div id="CanvasArea">
        <div id="Position1Hider" class="canvasHider"></div>
        <div id="Position2Hider" class="canvasHider"></div>
        <div id="Position3Hider" class="canvasHider"></div>
        <canvas id="DrawingCanvas" width="900" height="480" style="border-style:solid;border-width:1px;border-color:black;"></canvas>
    </div>
    <div id="DrawingTools">
        <label><input type="radio" name="drawingTool" value="Draw" onclick="Game.selectDrawTool();" checked="checked" /> Draw</label><br />
        <label><input type="radio" name="drawingTool" value="Erase" onclick="Game.selectEraseTool();" /> Erase</label><br />
    </div>
    <button id="ShowDrawing" type="button" onclick="Game.showMyArea();">Reveal My Area</button>
    <button id="HideDrawing" type="button" onclick="Game.hideMyArea();">Hide My Area</button>
    <button id="ClearMyArea" type="button" onclick="Game.clearMyArea();">Clear My Area</button>
    <button id="ClearAll" type="button" onclick="Game.clearAll();">Clear</button>
    <ul id="participantList"></ul>
    <div><i id="PressureSensitivityMessage">Pressure sensitivity currently only works in browsers that have implemented <a href="http://caniuse.com/#search=pointermove">pointer events</a> (sorry)</i></div>
</div>

<script src="~/Scripts/jquery.signalR-2.1.2.min.js"></script>
<script src="~/signalr/hubs"></script>

<script>
    var Lobby = {};
    var Game = {};

    var drawing;

    $(document).ready(function () {
        drawing = $.connection.drawingHub;
        Lobby.initialize();
        Game.initialize();
        $.connection.hub.start().done(function () {
            $("#JoinGameButton").show();
            drawing.server.joinLobby();
        });
    });

    Lobby.initialize = function () {
        drawing.client.updateLobby = Lobby.updateLobby;
    };

    Lobby.joinOrCreateGame = function () {
        var gameName = $("#GameName").val().trim();
        if (gameName == "") {
            alert("Please enter a game name.");
            return;
        }

        Lobby.joinGame(gameName);
    };

    Lobby.joinGame = function (gameName) {
        var username = prompt("Enter your name", "Harry Potter");

        if (username == null || username == "") {
            alert("Please enter a username.");
            return;
        }

        // TO DO - display a waiting indicator and disable things
        drawing.server.join(gameName, username);
    }

    Lobby.updateLobby = function (openGames) {
        console.log("Updating game list.");
        $("#gameList li").remove();

        if (openGames.length == 0)
            $("#gameList").append("<li>No open games found. Start your own!</li>");
        else
            $.each(openGames, function (index, value) {
                $("#gameList").append("<li><a href='#' onclick='Lobby.joinGame(\"" + value + "\");'>" + value + "</a></li>");
            });
    };

    Game.initialize = function () {
        Game.isDrawing = false;
        Game.previousX = 0;
        Game.previousY = 0;
        Game.currentX = 0;
        Game.currentY = 0;
        Game.eraserSelected = false;
        Game.isDrawing = false;
        Game.strokeStyle = "black";
        Game.lineWidth = 2;
        Game.eraseWidth = 20;
        Game.name = "unnamed";
        Game.drawingBoundaries = {
            startX: 0,
            endX: 900
        };

        Game.canvas = $("#DrawingCanvas")[0];
        Game.canvasContext = Game.canvas.getContext("2d");

        if ("onpointermove" in window && "onpointerdown" in window) {
            Game.canvas.addEventListener("pointermove", Game.mouseMove, false);
            Game.canvas.addEventListener("pointerdown", Game.mouseDown, false);
            $("#PressureSensitivityMessage").hide();
        }
        else { 
            Game.canvas.addEventListener("mousemove", Game.mouseMove, false);
            Game.canvas.addEventListener("mousedown", Game.mouseDown, false);
        }

        Game.canvas.addEventListener("mouseup", Game.mouseUpOrOut, false);
        Game.canvas.addEventListener("mouseout", Game.mouseUpOrOut, false);

        drawing.client.updateCanvas = Game.updateCanvas;
        drawing.client.displayMessage = Game.displayMessage;
        drawing.client.setPosition = Game.setPosition;
        drawing.client.updateParticipants = Game.updateParticipants;
        drawing.client.startGame = Game.startGame;
        drawing.client.joinedGame = Game.joinedGame;
        drawing.client.addPoint = Game.addPoint;
        drawing.client.revealDrawing = Game.revealDrawing;
        drawing.client.hideDrawing = Game.hideDrawing;
        drawing.client.clearDrawing = Game.clearDrawing;

        Game.canvasContext.fillText("Waiting for more people to join...", 10, 10);
        Game.canvasContext.fillText("Drawing will reset once 3 people are here.", 10, 30);
    };

    Game.joinedGame = function (gameName) {
        console.log("Joined game " + gameName);
        $("#LobbyContainer").hide();
        $("#GameContainer").show();
    };

    Game.startGame = function () {
        console.log("Game started.");
        Game.drawingBoundaries.startX = Game.position * 300;
        Game.drawingBoundaries.endX = (Game.position * 300) + 300;
        Game.clearCanvas();

        if(Game.position != 0)
            $("#Position1Hider").show();
        if (Game.position != 1)
            $("#Position2Hider").show();
        if (Game.position != 2)
            $("#Position3Hider").show();

        $("#ShowDrawing").show();
        $("#ClearAll").hide();
        $("#ClearMyArea").show();
    };

    Game.updateParticipants = function (participants) {
        console.log("Updating participant list.");
        $("#participantList li").remove();
        $.each(participants, function (index, value) {
            $("#participantList").append("<li>" + value + "</li>");
        });
    };

    Game.displayMessage = function (message) {
        alert(message);
    };

    Game.setPosition = function (pos) {
        console.log("Setting position to " + pos);
        Game.position = pos;
    };

    Game.updateCanvas = function (pX, pY, cX, cY, ss, lw) {
        Game.canvasContext.beginPath();
        Game.canvasContext.moveTo(pX, pY);
        Game.canvasContext.lineTo(cX, cY);
        Game.canvasContext.strokeStyle = ss;
        Game.canvasContext.lineWidth = lw;
        Game.canvasContext.stroke();
        Game.canvasContext.closePath();
    };

    Game.mouseMove = function (e) {
        if (Game.isDrawing) {
            Game.previousX = Game.currentX;
            Game.previousY = Game.currentY;
            //Game.currentX = e.clientX - Game.canvas.offsetLeft;
            //Game.currentY = e.clientY - Game.canvas.offsetTop;
            Game.currentX = e.layerX;
            Game.currentY = e.layerY;

            if (Game.currentX > Game.drawingBoundaries.endX)
                Game.currentX = Game.drawingBoundaries.endX;
            else if (Game.currentX < Game.drawingBoundaries.startX)
                Game.currentX = Game.drawingBoundaries.startX;

            Game.draw(e.pressure);
        }
    };

    Game.mouseDown = function (e) {
        Game.previousX = Game.currentX;
        Game.previousY = Game.currentY;
        //Game.currentX = e.clientX - Game.canvas.offsetLeft;
        //Game.currentY = e.clientY - Game.canvas.offsetTop;

        Game.currentX = e.layerX;
        Game.currentY = e.layerY;

        if (Game.currentX > Game.drawingBoundaries.endX)
            Game.currentX = Game.drawingBoundaries.endX;
        else if (Game.currentX < Game.drawingBoundaries.startX)
            Game.currentX = Game.drawingBoundaries.startX;

        Game.isDrawing = true;

        var pressure = e.pressure;
        var strokeStyle = Game.strokeStyle;
        var lineWidth = Game.lineWidth;
        if (pressure != undefined)
            lineWidth = Game.calculateLineWidthForPressure(pressure, 0);

        if (Game.eraserSelected) {
            strokeStyle = "white";
            lineWidth = Game.eraseWidth;
            if (pressure != undefined)
                lineWidth = Game.calculateLineWidthForPressure(pressure, 10);
        }
                
        drawing.server.addPoint(Game.currentX, Game.currentY, strokeStyle, lineWidth);
    };

    Game.addPoint = function (x, y, strokeStyle, lineWidth) {
        Game.canvasContext.beginPath();
        Game.canvasContext.fillStyle = strokeStyle;
        Game.canvasContext.fillRect(x, y, lineWidth, lineWidth);
        Game.canvasContext.closePath();
    };

    Game.mouseUpOrOut = function (e) {
        Game.isDrawing = false;
    };

    Game.draw = function (pressure) {
        var strokeStyle = Game.strokeStyle;
        var lineWidth = Game.lineWidth;
        if (pressure != undefined)
            lineWidth = Game.calculateLineWidthForPressure(pressure, 0);
        
        if (Game.eraserSelected) {
            strokeStyle = "white";
            lineWidth = Game.eraseWidth;
            if (pressure != undefined)
                lineWidth = Game.calculateLineWidthForPressure(pressure, 10);
        }       

        drawing.server.draw(Game.previousX, Game.previousY, Game.currentX, Game.currentY, strokeStyle, lineWidth);
    }

    Game.calculateLineWidthForPressure = function(pressure, defaultSize) {
        return defaultSize + (pressure * 5);
    }

    Game.clearCanvas = function () {
        Game.canvasContext.clearRect(0, 0, Game.canvas.width, Game.canvas.height);

        Game.drawPlayerAreas(); // TO DO - figure out why i need to draw it twice to be darker
        Game.drawPlayerAreas();
    };

    Game.drawPlayerAreas = function () {
        Game.drawLine(300, 5, 300, 480);
        Game.drawLine(600, 5, 600, 480);
    };

    Game.drawLine = function (startX, startY, endX, endY) {
        Game.canvasContext.setLineDash([5, 10]);

        Game.canvasContext.beginPath();
        Game.canvasContext.strokeStyle = "blue";
        Game.canvasContext.moveTo(startX, startY);
        Game.canvasContext.lineTo(endX, endY);
        Game.canvasContext.stroke();
        Game.canvasContext.closePath();

        Game.canvasContext.setLineDash([]);
    };
 
    Game.showMyArea = function () {
        drawing.server.showMyArea(Game.position);
        $("#ShowDrawing").hide();
        $("#HideDrawing").show();
    };

    Game.hideMyArea = function () {
        drawing.server.hideMyArea(Game.position);
        $("#HideDrawing").hide();
        $("#ShowDrawing").show();
    };

    Game.revealDrawing = function (position) {
        if (position == 0)
            $("#Position1Hider").hide();
        else if (position == 1)
            $("#Position2Hider").hide();
        else if (position == 2)
            $("#Position3Hider").hide();
    };

    Game.hideDrawing = function (position) {
        if (position == 0)
            $("#Position1Hider").show();
        else if (position == 1)
            $("#Position2Hider").show();
        else if (position == 2)
            $("#Position3Hider").show();
    };

    Game.clearMyArea = function () {
        drawing.server.clearMyArea(Game.position);
    }

    Game.clearDrawing = function (position, drawAreas) {
        var sectionWidth = 300;
        var offsetX = 300 * position;

        Game.canvasContext.clearRect(offsetX, 0, offsetX + 300, Game.canvas.height);
        if(drawAreas)
            Game.drawPlayerAreas();
    };

    Game.clearAll = function () {
        drawing.server.clearAll();
    };

    Game.selectEraseTool = function () {
        Game.eraserSelected = true;
    };

    Game.selectDrawTool = function () {
        Game.eraserSelected = false;
    };

    

</script>

Source/SignalRTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Drawing thing", "Index", "Drawing", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            
        </footer>
    </div>

    
</body>
</html>